### ISSUE TITLE
a20 After Siren Head was killed created infinite Geiger noises that got progressively louder

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [arramus/Snufkin-Custom-Zombies-Plus-A20-2021Dec07#1]
Hey so for a20 after killing siren zombie the game kept making Geiger noises that progressively got louder and louder. I even entered god mode to check if something was invisible and it didn't appear anything was near or even remotely present. Not sure why this is happening. https://gist.github.com/P3rf3ctXZer0/f6c45ae241398db1160e4a19e626ff51 here I included a gist of the log. It is not really helpful as no errors actually stand out.

**Comment by arramus** [comment]
Thank you. This is very much an experimental test release for A20 just to check for bugs and how it works with the new game dynamics and you've found one one of those annoying types. We had one like this with A19 where the flame effect sound just kept looping and didn't have its own kill switch. We'll visit some dedicated servers running the Snufkins once they are set up and see what's happening in more detail.

**Comment by P3rf3ctXZer0** [comment]
I have one if you wanted to mess around I don't care if it breaks.

**Comment by arramus** [comment]
Thank you. You are welcome to share your IP and I'll be able to visit you. This mod has been updated with a temporary workaround (that may become long term if there are no other solutions). Basically, as you will have experienced, there are 3 Geiger sounds.

A from 35 blocks
B from 25 blocks
C from 15 blocks

They can all stack for the increased volume but are supposed to purge each other as you move into different block range. And with the Siren being eliminated all should stop. This works on a 'buff' process where one triggers the other and so on. In A18 when Snufkin released this mod all was well, and the A19 update was seamless. A20 is not liking it at all.

For now, sound C, the 'radiation kill sound' initiates from 25 blocks and is the only one. After eliminating the Siren it is stopping each time I have tested so far. I am hopeful it will also be just fine on a dedicated server. I used a Windows dedicated server using Windows Game Server Manager 'WGSM'. It's similar to the Linux version BUT it doesn't allow manually setting the beta experimental version and I can only use that when it becomes stable. Back to SteamCMD and manually starting. I will appreciate a run through on your set up for sure.

**Comment by arramus** [comment]
I shall close this issue for now since feedback from a few servers has been positive so far on the simple workaround.
We'll see what the stable version of A20 updates and if it increase buff responsiveness. By all means reopen if necessary.
